package cn.ct.cloud.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.loginacct
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String loginacct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.userpswd
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String userpswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.username
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.email
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.authstatus
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private Byte authstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.usertype
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private Byte usertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.realname
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.cardnum
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String cardnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.accttype
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private Byte accttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.loginacct
     *
     * @return the value of member.loginacct
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getLoginacct() {
        return loginacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.loginacct
     *
     * @param loginacct the value for member.loginacct
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setLoginacct(String loginacct) {
        this.loginacct = loginacct == null ? null : loginacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.userpswd
     *
     * @return the value of member.userpswd
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.userpswd
     *
     * @param userpswd the value for member.userpswd
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd == null ? null : userpswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.username
     *
     * @return the value of member.username
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.username
     *
     * @param username the value for member.username
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.email
     *
     * @return the value of member.email
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.email
     *
     * @param email the value for member.email
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.authstatus
     *
     * @return the value of member.authstatus
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public Byte getAuthstatus() {
        return authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.authstatus
     *
     * @param authstatus the value for member.authstatus
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setAuthstatus(Byte authstatus) {
        this.authstatus = authstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.usertype
     *
     * @return the value of member.usertype
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public Byte getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.usertype
     *
     * @param usertype the value for member.usertype
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setUsertype(Byte usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.realname
     *
     * @return the value of member.realname
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.realname
     *
     * @param realname the value for member.realname
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.cardnum
     *
     * @return the value of member.cardnum
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getCardnum() {
        return cardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.cardnum
     *
     * @param cardnum the value for member.cardnum
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setCardnum(String cardnum) {
        this.cardnum = cardnum == null ? null : cardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.accttype
     *
     * @return the value of member.accttype
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public Byte getAccttype() {
        return accttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.accttype
     *
     * @param accttype the value for member.accttype
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setAccttype(Byte accttype) {
        this.accttype = accttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone
     *
     * @return the value of member.phone
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone
     *
     * @param phone the value for member.phone
     *
     * @mbg.generated Mon Sep 23 22:41:13 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}