server:
  port: 2000

  #配置数据源
spring:
  application:
    name: database-provider #当前微服务名称，注册服务信息时必须有
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.247.129:3306/distributed-crowd?useSSL=false&useUnicode=true&characterEncoding=UTF-8&?serverTimezone=Asia/Shanghai
#配置mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #开启驼峰
  configuration:
    map-underscore-to-camel-case: true
    #开启缓存
    cache-enabled: true
#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
  instance:
    prefer-ip-address: true